# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-27 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=200)),
                ('placeId', models.IntegerField(default=None)),
                ('rating', models.FloatField(default=0.0)),
            ],
        ),
        migrations.RemoveField(
            model_name='entry',
            name='user',
        ),
        migrations.DeleteModel(
            name='Entry',
        ),
    ]
