# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-28 07:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_system', '0002_auto_20180127_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='placeId',
            field=models.CharField(max_length=200),
        ),
    ]
